# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ZopNow.Engineering
email: tech@zopnow.com
description: > # this means to ignore newlines until "baseurl:"
    ZopNow is the largest online grocery store in India. We are operational in Mumbai, Bangalore, 
    Delhi, Gurgaon, Hyderabad, Pune and AWS.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://zopnow.engineering" # the base hostname & protocol for your site
twitter_username: zopnow
github_username:  zopnow

# Build settings
markdown: kramdown
